apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-mysql-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mysql-exporter
  template:
    metadata:
      labels:
        app: my-mysql-exporter
    spec:
      containers:
        - name: my-mysql-exporter
          image: public.ecr.aws/j6t1t8s7/my-mysql-exporter:latest
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-mysql-exporter-service
spec:
  selector:
    app: my-mysql-exporter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: monitoring
